events{}

http {

    upstream node_list {
        least_conn;

        server node_app1:3000;
        server node_app2:3001;
        server node_app3:3002 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://node_list;
        }
    }
}