events {}

http {

    proxy_cache_path 
        /tmp/cache 
            levels=1:2 
            keys_zone=mycache:10m 
            max_size=10m 
            inactive=60m 
            use_temp_path=off;

    server {
        listen 80;
        
        # Header to see HIT / MISS in browser network tab
        add_header X-Cache-Status $upstream_cache_status;

        # PROXY as the default root (matches what React Router expects)
        location / {
            proxy_pass https://snakes-guide.vercel.app/;

            # CRITICAL: Vercel needs these to know which app to serve
            proxy_ssl_server_name on;
            proxy_set_header Host snakes-guide.vercel.app;

            proxy_ignore_headers Cache-Control;
            access_log off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_cache mycache;
            proxy_cache_valid 200 5m;
        }

        # Keep this! It caches your frontend assets for an hour instead of 5 mins
        location /assets/ {
            proxy_pass https://snakes-guide.vercel.app/assets/;
            
            proxy_ssl_server_name on;
            proxy_set_header Host snakes-guide.vercel.app;
            
            proxy_cache mycache;
            proxy_cache_valid 200 1h; 
        }
    }
}